rename init_db -> create_kernel_files

diff --git a/create_kernel_files b/create_kernel_files
--- a/create_kernel_files
+++ b/create_kernel_files
@@ -25,6 +25,9 @@ txtwht=$(tput setaf 7)    # White
 txtrst=$(tput sgr0)       # Text reset
 
 
+
+
+
 DEBUG=1
 i=1
 spin()
@@ -57,34 +60,43 @@ dbg()
 }
 
 
-
-populate_version()
+usage()
 {
-	OLD_VERSION=$1
-	NEW_VERSION=$2
-
-	mkdir "${NEW_VERSION}"
-	pwd=$(pwd)
-
-	logn "${txtgrn}Creating directory for kernel version ${txtylw}${NEW_VERSION}${txtrst}   "
-	cd "${KERNEL_DIR}"
-	for commit in $(git rev-list --reverse --no-merges v${OLD_VERSION}..v${NEW_VERSION}); do
-		#log "${txtgrn}${commit}${txtrst}	"
-		spin
-		git log -1 --format='%B' "${commit}" > "${pwd}"/"${NEW_VERSION}"/${commit}
-	done
-	log ""
-
-	cd "${pwd}"
+	echo "version numbers not found"
+	echo "usage:"
+	echo "	$0 OLD_KERNEL NEW_KERNEL"
+	exit 1
 }
 
+OLD_VERSION=$1
+NEW_VERSION=$2
 
-populate_version 4.0 4.1
-populate_version 4.1 4.2
-populate_version 4.2 4.3
-populate_version 4.3 4.4
-populate_version 4.4 4.5
-populate_version 4.5 4.6
-populate_version 4.6 4.7
-populate_version 4.7 4.8
-populate_version 4.8 4.9
+
+if [ "${OLD_VERSION}" == "" ] ; then
+	usage
+fi
+
+if [ "${NEW_VERSION}" == "" ] ; then
+	usage
+fi
+
+# test if version is already created
+if [ -d "${NEW_VERSION}/" ] ; then
+	echo "${NEW_VERSION} files already created"
+	exit 1
+fi
+
+mkdir "${NEW_VERSION}"
+pwd=$(pwd)
+
+logn "${txtgrn}Creating directory for kernel version ${txtylw}${NEW_VERSION}${txtrst}   "
+cd "${KERNEL_DIR}"
+for commit in $(git rev-list --reverse --no-merges v${OLD_VERSION}..v${NEW_VERSION}); do
+	#log "${txtgrn}${commit}${txtrst}	"
+	spin
+	git log -1 --format='%B' "${commit}" > "${pwd}"/"${NEW_VERSION}"/${commit}
+done
+log ""
+
+cd "${pwd}"
+
