find_fixes_in_queue: mutithread it!

diff --git a/find_fixes_in_queue b/find_fixes_in_queue
--- a/find_fixes_in_queue
+++ b/find_fixes_in_queue
@@ -39,6 +39,57 @@ save_commit()
 	git show --pretty=email "${commit}" | sed -e "s/\[PATCH\]/\[PATCH ${version}\]/" >> "${mbox}"
 }
 
+check_patch()
+{
+	local patch
+	patch=$1
+
+	cd "${STABLE_QUEUE}/queue-${KERNEL_VERSION}/"
+	upstream=$(cat ${patch} | awk '{if(NR>1)print}' | grep -E -o '[0-9a-f]{40}' | head -n 1)
+	if [ "${upstream}" == "" ] ; then
+		return
+	fi
+
+	# shorten the commit
+	cd ${STABLE_TREE}
+	commit=$(git show -s --abbrev-commit --abbrev=12 --pretty=format:"%h" "${upstream}")
+	if [ "${commit}" == "" ] ; then
+		log "${txtred}commit ${upstream} not found!${txtrst}"
+		return
+	fi
+
+	cd ${STABLE_TREE}
+	if [ "${commit}" == "upstream" ] ; then
+		return
+	fi
+
+	message="${txtcyn}looking at ${txtgrn}${commit}${txtrst} "
+	result=$(${ID_FIXED_IN} ${commit})
+	retval=$?
+	if [ $retval -ne 0 ] ; then
+		log "${message}${txtpur}no fixes${txtrst}"
+		return
+	fi
+
+	for line in ${result}; do
+		line_array=(${line//:/ })
+		sha1=${line_array[0]}
+		kernel_version=${line_array[1]}
+		commit_id=${line_array[2]}
+		message+="${txtred}fix found in ${txtylw}${kernel_version}${txtrst} "
+
+		# see if commit is already in the queue
+		found=$(grep -l -r "${commit_id}" "${STABLE_QUEUE}/queue-${KERNEL_VERSION}/")
+		if [ "${found}" == "" ] ; then
+			save_commit "${commit_id}" "${kernel_version}" "${MBOX}"
+			message+="${txtgrn}saved"
+		else
+			message+="${txtblu}already in queue"
+		fi
+	done
+	log "${message}"
+}
+
 KERNEL_VERSION=$1
 
 if [ "${KERNEL_VERSION}" == "" ] ; then
@@ -50,41 +101,9 @@ MBOX=$(mktemp ${TMP_PREFIX}mbox.XXXXXX) || exit 1
 cd "${STABLE_QUEUE}/queue-${KERNEL_VERSION}/"
 
 for patch in *.patch ; do
-	cd "${STABLE_QUEUE}/queue-${KERNEL_VERSION}/"
-	upstream=$(cat ${patch} | awk '{if(NR>1)print}' | grep -E -o '[0-9a-f]{40}' | head -n 1)
-	if [ "${upstream}" == "" ] ; then
-		continue
-	fi
-
-	# shorten the commit
-	cd ${STABLE_TREE}
-	commit=$(git show -s --abbrev-commit --abbrev=12 --pretty=format:"%h" "${upstream}")
-	if [ "${commit}" == "" ] ; then
-		log "${txtred}commit ${upstream} not found!${txtrst}"
-		continue
-	fi
-
-	cd ${STABLE_TREE}
-	if [ "${commit}" == "upstream" ] ; then
-		continue
-	fi
-	logn "${txtcyn}looking at ${txtgrn}${commit}${txtrst}	"
-	result=$(${ID_FIXED_IN} ${commit})
-	retval=$?
-	if [ $retval -ne 0 ] ; then
-		log "${txtpur}no fixes${txtrst}"
-		continue
-	fi
-	for line in ${result}; do
-		line_array=(${line//:/ })
-		sha1=${line_array[0]}
-		kernel_version=${line_array[1]}
-		commit_id=${line_array[2]}
-		logn "${txtred}fix found in ${txtylw}${kernel_version} "
-		save_commit "${commit_id}" "${kernel_version}" "${MBOX}"
-	done
-	log ""
+	check_patch $patch &
 done
+wait
 
 echo "# commits are in ${MBOX}"
 echo "mutt -f ${MBOX}"
