fixed_in: minor tweaks to go faster and look prettier

diff --git a/fixed_in b/fixed_in
--- a/fixed_in
+++ b/fixed_in
@@ -78,8 +78,8 @@ fi
 cd "${KERNEL_DIR}"
 unified_sha1=$(git show -s --abbrev-commit --abbrev=12 --pretty=format:"%h" "${sha1}" 2>/dev/null)
 if [ "${unified_sha1}" = "" ] ; then
-	echo "${sha1} not found"
-	exit 1
+	log "${txtylw}${sha1}${txtred} not found in upstream repo${txtrst}"
+	exit 2
 fi
 
 sha1=${unified_sha1}
@@ -87,14 +87,14 @@ sha1=${unified_sha1}
 cd "${COMMIT_TREE_DIR}"
 
 found=0
-for commit in $(git grep -l "${sha1}"); do
+for commit in $(git grep -l --threads=3 "${sha1}"); do
 #	logn "${txtylw}${sha1}${txtgrn} found in ${txtred}${commit}	"
 	kernel_ver=$(echo "${commit}" | cut -f 1 -d '/')
 	commit_id=$(echo "${commit}" | cut -f 2 -d '/')
 
 #	log "${txtblu}${kernel_ver}	${commit_id}"
 
-	logn "${txtylw}${sha1}${txtgrn} fixed in kernel "
+	logn "${txtcyn}${sha1}${txtgrn} fixed in kernel "
 	logn "${txtpur}${kernel_ver}${txtgrn} in commit "
 	log  "${txtred}${commit_id}${txtrst}"
 	found=1
@@ -104,4 +104,5 @@ if [ "${found}" = "1" ] ; then
 	exit
 fi
 
-echo "not found!"
+dbg "${txtylw}${sha1}${txtgrn} no fixes found${txtrst}"
+exit 1
